<a href="https://colab.research.google.com/github/trishanirmala/Development-of-Interactive-Cyber-Threat-Visualization-Dashboard/blob/main/SQL_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SQL_Task



*   **SQL Definition**: Structured Query Language is the standard language for managing and manipulating relational databases.
*   **SQL Use**: Used to store, retrieve, manage, and organize data efficiently within relational databases.
*   **Real-world Usage**: Powers data management in applications like social media platforms, e-commerce sites, and banking systems.
*   **DDL (Data Definition Language)**: Commands for defining and modifying the database structure (e.g., `CREATE`, `ALTER`, `DROP`).
*   **DML (Data Manipulation Language)**: Commands for managing data within database objects (e.g., `SELECT`, `INSERT`, `UPDATE`, `DELETE`).
*   **DCL (Data Control Language)**: Commands for controlling database access and permissions (e.g., `GRANT`, `REVOKE`).
*   **TCL (Transaction Control Language)**: Commands for managing database transactions to ensure data integrity (e.g., `COMMIT`, `ROLLBACK`).

## SQL Data Types Notes

*   **SQL Data Types Definition**: Data types classify the kind of values that can be stored in a column, defining the range and type of data.
*   **INT**: Used for storing whole numbers (integers).
*   **VARCHAR**: Used for storing variable-length character strings (text).
*   **DATE**: Used for storing date values (year, month, day).
*   **FLOAT**: Used for storing approximate floating-point numbers (decimal numbers).
*   **BOOLEAN**: Used for storing true/false or 0/1 values.

**CREATE TABLE**: Used to create a new table in the database with specified columns and data types.

**INSERT INTO**: Used to add records (rows) into an existing table.

**FOR EXAMPLE**:Student Table

In [ ]:
import sqlite3
from IPython.display import display
import pandas as pd

# Create SQLite connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create Students table
cursor.execute("""
CREATE TABLE Students (
    ID INTEGER PRIMARY KEY,
    Name TEXT,
    Age INTEGER,
    Gender TEXT,
    Department TEXT,
    Marks INTEGER,
    City TEXT
)
""")

# Insert sample records
cursor.executemany("""
INSERT INTO Students VALUES (?, ?, ?, ?, ?, ?, ?)
""", [
    (1, 'Alice', 20, 'Female', 'CSE', 85, 'Chennai'),
    (2, 'Bob', 21, 'Male', 'ECE', 78, 'Bangalore'),
    (3, 'Charlie', 19, 'Male', 'IT', 88, 'Hyderabad'),
    (4, 'Diana', 22, 'Female', 'CSE', 92, 'Coimbatore'),
    (5, 'Eve', 20, 'Female', 'EEE', 74, 'Madurai')
])

# Fetch and display table
df = pd.read_sql_query("SELECT * FROM Students", conn)
display(df)

   ID     Name  Age  Gender Department  Marks        City
0   1    Alice   20  Female        CSE     85     Chennai
1   2      Bob   21    Male        ECE     78   Bangalore
2   3  Charlie   19    Male         IT     88   Hyderabad
3   4    Diana   22  Female        CSE     92  Coimbatore
4   5      Eve   20  Female        EEE     74     Madurai

**SELECT with WHERE Conditions**

**SELECT**: Used to retrieve specific columns or records from a table.

**WHERE**: Used to filter records based on conditions.

**AND**: Used to combine multiple conditions in a query.

In [ ]:
# SELECT specific columns from the Students table
query1 = "SELECT Name, Department, Marks FROM Students"
df1 = pd.read_sql_query(query1, conn)
display(df1)

# SELECT students who scored more than 80 marks using WHERE clause
query2 = "SELECT * FROM Students WHERE Marks > 80"
df2 = pd.read_sql_query(query2, conn)
display(df2)

# SELECT students from CSE department using WHERE condition
query3 = "SELECT * FROM Students WHERE Department = 'CSE'"
df3 = pd.read_sql_query(query3, conn)
display(df3)

# SELECT students with marks greater than 80 AND age less than 22
query4 = "SELECT * FROM Students WHERE Marks > 80 AND Age < 22"
df4 = pd.read_sql_query(query4, conn)
display(df4)

      Name Department  Marks
0    Alice        CSE     85
1      Bob        ECE     78
2  Charlie         IT     88
3    Diana        CSE     92
4      Eve        EEE     74

   ID     Name  Age  Gender Department  Marks        City
0   1    Alice   20  Female        CSE     85     Chennai
1   3  Charlie   19    Male         IT     88   Hyderabad
2   4    Diana   22  Female        CSE     92  Coimbatore

   ID   Name  Age  Gender Department  Marks        City
0   1  Alice   20  Female        CSE     85     Chennai
1   4  Diana   22  Female        CSE     92  Coimbatore

   ID     Name  Age  Gender Department  Marks       City
0   1    Alice   20  Female        CSE     85    Chennai
1   3  Charlie   19    Male         IT     88  Hyderabad

**Aggregate Functions:**

**COUNT()**: Returns the total number of records.

**SUM():** Returns the total sum of a numeric column.

**AVG():** Returns the average value of a numeric column.

**MIN():** Returns the minimum value in a column.

**MAX():** Returns the maximum value in a column.

In [ ]:
# COUNT the total number of students
query1 = "SELECT COUNT(*) AS Total_Students FROM Students"
df1 = pd.read_sql_query(query1, conn)
display(df1)

# SUM of marks of all students
query2 = "SELECT SUM(Marks) AS Total_Marks FROM Students"
df2 = pd.read_sql_query(query2, conn)
display(df2)

# AVERAGE marks of students
query3 = "SELECT AVG(Marks) AS Average_Marks FROM Students"
df3 = pd.read_sql_query(query3, conn)
display(df3)

# MINIMUM marks obtained
query4 = "SELECT MIN(Marks) AS Minimum_Marks FROM Students"
df4 = pd.read_sql_query(query4, conn)
display(df4)

# MAXIMUM marks obtained
query5 = "SELECT MAX(Marks) AS Maximum_Marks FROM Students"
df5 = pd.read_sql_query(query5, conn)
display(df5)

   Total_Students
0               5

   Total_Marks
0          417

   Average_Marks
0           83.4

   Minimum_Marks
0             74

   Maximum_Marks
0             92

**GROUP BY:** Groups records that have the same values in a column.

**HAVING:** Filters grouped records based on aggregate conditions.

**Difference:** WHERE filters rows, HAVING filters groups.

In [ ]:
 # GROUP students by Department and calculate average marks
query1 = """
SELECT Department, AVG(Marks) AS Average_Marks
FROM Students
GROUP BY Department
"""
df1 = pd.read_sql_query(query1, conn)
display(df1)

# GROUP BY with HAVING to show departments with average marks above 80
query2 = """
SELECT Department, AVG(Marks) AS Average_Marks
FROM Students
GROUP BY Department
HAVING AVG(Marks) > 80
"""
df2 = pd.read_sql_query(query2, conn)
display(df2)

  Department  Average_Marks
0        CSE           88.5
1        ECE           78.0
2        EEE           74.0
3         IT           88.0

  Department  Average_Marks
0        CSE           88.5
1         IT           88.0

**ORDER BY: **Sorts the result set in ascending or descending order.

**ASC:** Sorts data in ascending order (default).

**DESC:** Sorts data in descending order.

**LIMIT:** Restricts the number of records displayed.

In [ ]:
# ORDER students by Marks in ascending order
query1 = "SELECT * FROM Students ORDER BY Marks ASC"
df1 = pd.read_sql_query(query1, conn)
display(df1)

# ORDER students by Marks in descending order
query2 = "SELECT * FROM Students ORDER BY Marks DESC"
df2 = pd.read_sql_query(query2, conn)
display(df2)

# Display only top 3 students based on highest marks
query3 = "SELECT * FROM Students ORDER BY Marks DESC LIMIT 3"
df3 = pd.read_sql_query(query3, conn)
display(df3)

   ID     Name  Age  Gender Department  Marks        City
0   5      Eve   20  Female        EEE     74     Madurai
1   2      Bob   21    Male        ECE     78   Bangalore
2   1    Alice   20  Female        CSE     85     Chennai
3   3  Charlie   19    Male         IT     88   Hyderabad
4   4    Diana   22  Female        CSE     92  Coimbatore

   ID     Name  Age  Gender Department  Marks        City
0   4    Diana   22  Female        CSE     92  Coimbatore
1   3  Charlie   19    Male         IT     88   Hyderabad
2   1    Alice   20  Female        CSE     85     Chennai
3   2      Bob   21    Male        ECE     78   Bangalore
4   5      Eve   20  Female        EEE     74     Madurai

   ID     Name  Age  Gender Department  Marks        City
0   4    Diana   22  Female        CSE     92  Coimbatore
1   3  Charlie   19    Male         IT     88   Hyderabad
2   1    Alice   20  Female        CSE     85     Chennai

**JOIN:** Used to combine rows from two tables based on a related column.

**INNER JOIN:** Returns matching records from both tables.

**LEFT JOIN:** Returns all records from the left table and matching records from the right table.

In [ ]:
# Create Departments table
cursor.execute("""
CREATE TABLE Departments (
    Department TEXT PRIMARY KEY,
    HOD TEXT
)
""")

# Insert records into Departments table
cursor.executemany("""
INSERT INTO Departments VALUES (?, ?)
""", [
    ('CSE', 'Dr. Kumar'),
    ('ECE', 'Dr. Rao'),
    ('IT', 'Dr. Meena'),
    ('EEE', 'Dr. Sharma')
])

# INNER JOIN between Students and Departments
query1 = """
SELECT Students.Name, Students.Department, Departments.HOD
FROM Students
INNER JOIN Departments
ON Students.Department = Departments.Department
"""
df1 = pd.read_sql_query(query1, conn)
display(df1)

# LEFT JOIN between Students and Departments
query2 = """
SELECT Students.Name, Students.Department, Departments.HOD
FROM Students
LEFT JOIN Departments
ON Students.Department = Departments.Department
"""
df2 = pd.read_sql_query(query2, conn)
display(df2)

      Name Department         HOD
0    Alice        CSE   Dr. Kumar
1      Bob        ECE     Dr. Rao
2  Charlie         IT   Dr. Meena
3    Diana        CSE   Dr. Kumar
4      Eve        EEE  Dr. Sharma

      Name Department         HOD
0    Alice        CSE   Dr. Kumar
1      Bob        ECE     Dr. Rao
2  Charlie         IT   Dr. Meena
3    Diana        CSE   Dr. Kumar
4      Eve        EEE  Dr. Sharma

**SELF JOIN:** A join where a table is joined with itself.

**OUTER JOIN:** Returns matching records and also non-matching records from one or both tables.

**LEFT OUTER JOIN:** Returns all records from the left table and matching records from the right table.

**RIGHT OUTER JOIN:** Returns all records from the right table and matching records from the left table.

In [ ]:
# SELF JOIN on Students table to compare students from the same department
query1 = """
SELECT A.Name AS Student1, B.Name AS Student2, A.Department
FROM Students A
JOIN Students B
ON A.Department = B.Department
AND A.ID <> B.ID
"""
df1 = pd.read_sql_query(query1, conn)
display(df1)

# LEFT OUTER JOIN between Students and Departments
query2 = """
SELECT Students.Name, Students.Department, Departments.HOD
FROM Students
LEFT OUTER JOIN Departments
ON Students.Department = Departments.Department
"""
df2 = pd.read_sql_query(query2, conn)
display(df2)

  Student1 Student2 Department
0    Alice    Diana        CSE
1    Diana    Alice        CSE

      Name Department         HOD
0    Alice        CSE   Dr. Kumar
1      Bob        ECE     Dr. Rao
2  Charlie         IT   Dr. Meena
3    Diana        CSE   Dr. Kumar
4      Eve        EEE  Dr. Sharma

**Subquery:** A query written inside another SQL query.

**Purpose:** Used to filter or compare values based on another query result.

In [ ]:
# Select students who scored more than the average marks
query1 = """
SELECT *
FROM Students
WHERE Marks > (
    SELECT AVG(Marks)
    FROM Students
)
"""
df1 = pd.read_sql_query(query1, conn)
display(df1)

   ID     Name  Age  Gender Department  Marks        City
0   1    Alice   20  Female        CSE     85     Chennai
1   3  Charlie   19    Male         IT     88   Hyderabad
2   4    Diana   22  Female        CSE     92  Coimbatore

**VIEW:** A virtual table created using a SELECT query.

In [ ]:
# Create a view for students with marks above 80
cursor.execute("""
CREATE VIEW HighScorers AS
SELECT Name, Department, Marks
FROM Students
WHERE Marks > 80
""")

# Retrieve data from the view
df = pd.read_sql_query("SELECT * FROM HighScorers", conn)
display(df)

      Name Department  Marks
0    Alice        CSE     85
1  Charlie         IT     88
2    Diana        CSE     92

**TRANSACTION:** A set of SQL operations executed as a single unit

In [ ]:
# Update marks of a student (transaction starts automatically)
cursor.execute("UPDATE Students SET Marks = 90 WHERE ID = 2")

# Rollback the transaction
conn.rollback()

# Display table after rollback
df = pd.read_sql_query("SELECT * FROM Students", conn)
display(df)

Empty DataFrame
Columns: [ID, Name, Age, Gender, Department, Marks, City]
Index: []